import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import axios from "axios";

export default function Home() {
  const { data: session, status } = useSession();
  const [user, setUser] = useState(null);
  const [userBalance, setUserBalance] = useState(null);

  useEffect(() => {
    console.log(session);
  }, [session]);

  useEffect(() => {
    if (!session) return;

    axios
      .get(`http://localhost:3000/api/users/${session.user.username}`)
      .then((res) => {
        console.log("res", res);
        setUser(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, [session]);

  useEffect(() => {
    if (!user) return;

    const headers = {
      "Content-Type": "application/json",
      "X-Api-Key": user.in_key,
    };

    axios
      .get(`https://b75b808c74.d.voltageapp.io/api/v1/wallet`, { headers })
      .then((res) => {
        console.log("user wallet res", res);

        setUserBalance(res.data.balance / 1000);
      })
      .catch((err) => {
        console.log(err);
      });
  }, [user]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          {status} / Balance {userBalance}
        </h1>

        <button onClick={() => signIn()}>login</button>
        <button onClick={() => signOut()}>logout</button>
      </main>
    </>
  );
}
